### ISSUE TITLE
Encryptionmethod

### ISSUE THREAD

**Issue by melheim** [difi/idporten-validator-metadata#1]
```xml
<EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc">
  <xenc:KeySize xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">128</xenc:KeySize>
</EncryptionMethod>
````

Dette er eit valfritt felt, som godt ikkje treng vere med. Om det skal vere med må det bruke støtta EncryptionMethod og inneholde KeySize (som sikkert ogso skal vere innafor nokon rammer).

@oyri Kan du finne ut kva som er gyldig og støtta input i desse felta?

**Comment by klakegg** [comment]
Hvilke gyldige verdier eller grenseverdier er det som skal inne her? Kom gjerne også med eksempel på utfylling.

**Comment by melheim** [comment]
Dene er ok:
            <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc">
                <xenc:KeySize xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">128</xenc:KeySize>
			</EncryptionMethod>
        </KeyDescriptor>

Denne er ikkje ok:
            <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc">
			</EncryptionMethod>
        </KeyDescriptor>

Eg fant dette i OpenAM, men @oyri kan med fordel dobbeltsjekke:
For AES, key strengths of 128, 192, 256 are supported. For 3DES, 0, 112 or 168 are supported.

Det er ikkje mange som brukar 3DES.

**Comment by klakegg** [comment]
Hvilke URIer er gyldige for algoritme? AES128-CBC ser jeg, har du også 3DES?

**Comment by klakegg** [comment]
Fant den.
