### ISSUE TITLE
Sjekke om entityID er gyldig

### ISSUE THREAD

**Issue by melheim** [difi/idporten-validator-metadata#2]
<EntityDescriptor entityID="tttt" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">

Må validere felt opp mot det som er gyldig input i OpenAM og ldap-felt for entityID på tenesteeigar.

**Comment by aberner** [comment]
se diskusjon om dette internt i Difi, ref: PBLEID-11474

Er det Difi sin difi-saml-schema-metadata-2.0.xsd som skal brukes for å validere dette?

jeg oppfatter at norske tegn f.eks. ikke tillattes i entityID, men ser ikke at det er definert eksplisitt i xsd'n.

**Comment by melheim** [comment]
Mellomrom er ogso ei utfordring, samt nokre spesialteikn.
